### ISSUE TITLE
为什么我看好自出版

### ISSUE THREAD

**Issue by zhengjunwei** [zhengjunwei/blog#3]
我这几天在看新闻
新闻上说房子买给优惠国家补帖
非北京户口也可以买房在北京
电视里教会我们，只有大BOSS不喜欢的东西才会给小弟，所以我的看法是
未来这些我们现在在追求的东西将只会变得很廉价没有价值
就像我们当前追求黑白电视机一样，后来追求彩电
彩电最近流行什么？27忖
这意味着大部分家庭家里的电视又要淘汰了
我直接说我的看法：现在的资讯分二种
一种是付费， 一种是免费
我现在看好付费这块
也就是现在流行的词叫自出版
比如说你弄一个小博客不管是不是wordpress的
以前可能半年，二年，
OK，成了牛博了
未来成为牛博的可能性接近为零了
用户渴望的是付费的高品质的内容消费
所以，我在考虑能不能弄一个自出版的平台，可能性大不大
比如冷风，可以弄一本react的自出版的书
比如你，可以把你自由职业做的那个论坛前后弄的技术写下来
费用10块左右，20，肯定有人买单的
自出版的书是直接读者和作者一对一沟通，还可以像软件一样随时升级版本

**Comment by acetee** [comment]
这种项目已经又在几个在做了

**Comment by zhengjunwei** [comment]
恩，但是有一个风险，因为中国盗版比较严重，比如像我虽然入了kindle,但是我基本上没有在正规渠道买过什么电子书，我付费了一个电子书分享BBS，一年二十多块钱，我可以无限制下载书。
