### ISSUE TITLE
我的说说

### ISSUE THREAD

**Issue by moyu-edu** [zhengjunwei/blog#5]
![444](https://cloud.githubusercontent.com/assets/15145237/11911864/242c9d8e-a65f-11e5-8b71-c68c96dd48d2.jpg)

**Comment by zhengjunwei** [comment]
妈的，freecodecamp你就不能快一点吗？每次提交代码速度像屎一样

**Comment by zhengjunwei** [comment]
我懂了突然，每次一慢我就得切VPN

**Comment by zhengjunwei** [comment]
首先，你的记忆，决定你的表现，你的所有表现，都取自你的记忆！所以，你记住什么，不记住什么，决定了，你会有怎样的表现。换一句话来说，整个你的人生，最最根本的那个部分，取决于，你如何记忆！

**Comment by zhengjunwei** [comment]
恶心死了做题做得

**Comment by moyu-edu** [comment]
聊天室被印度人占领了，万恶的印度人学习太疯狂了

**Comment by moyu-edu** [comment]
Java的this取决于声明，javascript的this依赖于函数的调用方式

**Comment by moyu-edu** [comment]
john resig肯定懂日语

**Comment by moyu-edu** [comment]
正则表达式：分组、反向引用、正向捕获、反向捕获

**Comment by moyu-edu** [comment]
between the model and view,the watchers the digest loop

**Comment by moyu-edu** [comment]
$apply,$applhy
